//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunFatura.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Urun()
        {
            this.tbl_FaturaBilgi = new HashSet<tbl_FaturaBilgi>();
        }
    
        public int UrunId { get; set; }
        public Nullable<int> UrunNo { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FaturaBilgi> tbl_FaturaBilgi { get; set; }
    }
}
