//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunFatura.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Musteri()
        {
            this.tbl_Fatura = new HashSet<tbl_Fatura>();
        }
    
        public int MusteriId { get; set; }
        public int MusteriNo { get; set; }
        public string MusteriAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fatura> tbl_Fatura { get; set; }
    }
}
