//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunFatura.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Fatura()
        {
            this.tbl_FaturaBilgi = new HashSet<tbl_FaturaBilgi>();
        }
    
        public int FaturaId { get; set; }
        public int FaturaNo { get; set; }
        public Nullable<decimal> FaturaTutar { get; set; }
        public Nullable<int> MusteriNo { get; set; }
    
        public virtual tbl_Musteri tbl_Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FaturaBilgi> tbl_FaturaBilgi { get; set; }
    }
}
